title: personal web site of janos erdos
email: erdosj@gmail.com
description: >
  Personal web space.
baseurl: ""
url: "http://erdos.dev"
twitter_username: erdosjr
github_username:  erdos

# Build settings
markdown: kramdown
