#!/bin/sh

jekyll clean
git clone https://github.com/erdos/erdos.github.io.git -b master _site
jekyll build
git add .
git commit -m "auto commit"
#git remote add origin https://github.com/erdos/erdos.github.io.git

git push -f #--set-upstream origin master

cd ..
jekyll clean
