#!/bin/sh

jekyll clean
jekyll build
cd _site
git init
git add .

#git add .
git commit -m "auto commit"
git remote add origin https://github.com/erdos/erdos.github.io.git

git push -f --set-upstream origin master

cd ..
jekyll clean
